name: yu_health
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  device_preview: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.5.0
  get: ^4.6.6
  intl: ^0.18.0

dev_dependencies:
  bloc_test: ^9.1.2
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
  
  #^ METROPOLIS FONT:
  fonts:
    - family: Metropolis
      fonts:
        - asset: assets/fonts/Metropolis-Light.ttf
          weight: 300
        - asset: assets/fonts/Metropolis-Regular.ttf
          weight: 400
        - asset: assets/fonts/Metropolis-Medium.ttf
          weight: 500
        - asset: assets/fonts/Metropolis-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Metropolis-Bold.ttf
          weight: 700
        - asset: assets/fonts/Metropolis-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Metropolis-Black.ttf
          weight: 900
    - family: RedHat
      fonts:
        - asset: assets/fonts/RedHatText-Light.ttf
          weight: 300
        - asset: assets/fonts/RedHatText-Regular.ttf
          weight: 400
        - asset: assets/fonts/RedHatText-Medium.ttf
          weight: 500
        - asset: assets/fonts/RedHatText-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/RedHatText-Bold.ttf
          weight: 700

